name: inventory_repository
description: Dart package which manages the authentication domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies: 
  dio: ^4.0.0
  intl: ^0.17.0
  inventory_api:
    path: ../inventory_api
  json_annotation: ^4.0.1
  lint: ^1.5.3

dev_dependencies:
  build_runner: ^2.0.4
  coverage: ^1.0.3
  json_serializable: ^4.0.2
