include: package:lint/analysis_options.yaml

linter: 
  rules:
    - parameter_assignments
    - sort_pub_dependencies

analyser: 
  errors: 
    missing_required_params: error
    parameter_assignments: error
    missing_return: error
    sort_pub_dependencies: ignore
