include: package:lint/analysis_options.yaml

linter: 
  rules:
    - parameter_assignments

analyser:
  exclude:
    - "**/*.g.dart"
  errors:
    missing_required_params: error
    parameter_assignments: error
    missing_return: error
    sort_pub_dependencies: ignore