name: dsc_tools
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cached_network_image: ^3.1.0
  connectivity_plus: ^1.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dropdown_search: ^0.6.3
  easy_localization: ^3.0.0
  equatable: ^2.0.2
  excel: 2.0.0-null-safety-3
  firebase_analytics: ^8.2.0
  flutter_bloc: ^7.0.1
  firebase: ^9.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.0
  flutter_html_to_pdf: ^0.6.1
  flutter_launcher_icons: ^0.9.1
  firebase_remote_config: ^0.10.0+3
  flutter_svg: ^0.22.0
  flutter_webview_plugin: ^0.4.0
  freezed_annotation: ^0.14.2
  get: ^4.1.4
  get_storage: ^2.0.3
  horizontal_data_table: ^3.4.2
  image_picker: ^0.8.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  linked_scroll_controller: ^0.2.0
  lint: ^1.5.3
  loading_overlay: ^0.3.0
  logger: ^1.0.0
  lottie: ^1.0.1
  open_file: ^3.2.1
  package_info: ^2.0.2
  path_provider: ^2.0.2
  pdf: ^3.4.2
  permission_handler: ^8.1.2
  photo_view: ^0.12.0
  popover: ^0.2.6+1
  pretty_dio_logger: ^1.1.1
  printing: ^5.4.3
  retrofit: ^2.0.0
  retrofit_generator: ^2.0.0
  rxdart: ^0.27.1
  share: ^2.0.4
  shared_preferences: ^2.0.6
  tuple: ^2.0.0
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  freezed: ^0.14.1
  json_serializable: ^4.0.2
  change_app_package_name: ^1.0.0

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Adds code generation (synthetic package) support
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true  
  assets:
    - assets/icons/
    - assets/icons/tabs/
    - assets/icons/dashboard/
    - assets/json/
    - assets/images/
    - assets/lottie/
    - assets/animated/
    - .env
  fonts:
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
          weight: 400
      
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
