# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new iOS beta build to Firebase App Distribution"
    lane :ios_beta_app do
        build_app(
            scheme: "Runner",
            archive_path: "./build/Runner.xcarchive",
            export_method: "development",
            output_directory: "./build/Runner"
        )
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID"],
            firebase_cli_token: ENV["FIREBASE_TOKEN"],
            testers: "iamisathya@gmail.com",
            groups: "testers",
            release_notes: "Test release note",            
            ipa_path: "./build/Runner/Runner.ipa"
        )
    end
end
