# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new android beta build to Firebase App Distribution"
  gradle(
      task: 'assemble',
      build_type: 'Release'
  )
  lane :android_beta_app do
      firebase_app_distribution(
          app: ENV["FIREBASE_APP_ID"],
          firebase_cli_token: ENV["FIREBASE_TOKEN"],
          testers: "iamisathya@gmail.com",
          groups: "testers",
          release_notes: "Test release note",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
end
