name: easyship_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies: 
  equatable: ^2.0.3
  json_annotation: ^4.0.1
dev_dependencies:
  build_runner: ^2.0.4
